### ISSUE TITLE
Fine-tune a NLLB-200 model for translating

### ISSUE THREAD

**Issue by Bachstelze** [danielinux7/Caucasus-NLP-Data-Pipeline#108]
It is possible to use a pretrained translation model like NLLB and add the vocabulary for Abkhaz and then train it with the parallel data: https://cointegrated.medium.com/how-to-fine-tune-a-nllb-200-model-for-translating-a-new-language-a37fc706b865

**Comment by danielinux7** [comment]
Abkhazian was included to Google Translate, the main goal is achieved, so I m closing this issue.
